"""
tax_brain/agent/models.py

Data models for the Layer 4 CPA query agent.
"""
from __future__ import annotations

from pydantic import BaseModel, Field, ConfigDict


class RetrievedPassage(BaseModel):
    """
    A single passage retrieved from the knowledge base.

    This is the universal exchange format between the retriever,
    reranker, compressor, and synthesizer. Any retrieval backend
    (hierarchical, LightRAG, flat vector) must produce these.
    """
    source           : str   = "publication"  # "publication" | "rule" | "instruction" | "graph"
    layer            : int   = 0     # Legacy: 1=rules, 2=instructions, 3=publications. 0=unspecified.
    source_type      : str   = ""    # Finer-grained: "mef_rule" | "instruction_section" | etc.
    reference        : str   = ""    # IRS pub number, e.g. "596"
    title            : str           # pub title, e.g. "Earned Income Credit (EIC)"
    text             : str           # the retrieved passage text
    score            : float         # relevance score (0–1, higher = more relevant)
    page             : int   = 0     # page_start from the chunk
    chunk_id         : str   = ""    # chunk_id UUID
    chapter          : str   = ""    # chapter_title (may be empty)
    section          : str   = ""    # section_title (may be empty)
    retrieval_method : str   = "vector"   # "vector" | "bm25" | "hybrid"
    chunk_type       : str   = "detail"   # "pub_summary" | "section_summary" | "detail"
    topic_ids        : list[str] = Field(default_factory=list)
    context_annotation : str = ""         # LLM-generated context from ingestion

    @property
    def citation(self) -> str:
        """Short human-readable citation string."""
        parts = [f"IRS Pub {self.reference}"]
        if self.chapter:
            parts.append(self.chapter)
        elif self.section:
            parts.append(self.section)
        if self.page:
            parts.append(f"p. {self.page}")
        return " — ".join(parts)

    @property
    def snippet(self) -> str:
        """First 200 characters of the passage, stripped."""
        s = self.text.replace("\n", " ").strip()
        return s[:200] + ("…" if len(s) > 200 else "")


class QueryResult(BaseModel):
    """
    Complete result of a CPA query: retrieved contexts + synthesized answer.

    Attributes:
        query         : The original question.
        answer        : LLM-generated answer (empty string if synthesis was skipped).
        contexts      : Retrieved passages, ordered by relevance.
        retrieval_ms  : Wall-clock time for the retrieval step.
        synthesis_ms  : Wall-clock time for the LLM synthesis step.
        model_used    : OpenAI model string, e.g. "gpt-4o-mini".
        prompt_tokens : Tokens sent to the model.
        completion_tokens : Tokens generated by the model.
        error         : Non-empty if something went wrong during synthesis.
        query_intent  : Detected intent from the query classifier.
        detected_tax_year : Tax year detected by the classifier.
    """
    query             : str
    answer            : str
    contexts          : list[RetrievedPassage] = Field(default_factory=list)
    retrieval_ms      : float = 0.0
    synthesis_ms      : float = 0.0
    model_used        : str   = ""
    prompt_tokens     : int   = 0
    completion_tokens : int   = 0
    error             : str   = ""
    query_intent      : str   = ""
    detected_tax_year : int | None = None
    retrieval_mode    : str   = ""     # "hierarchical" | "flat" | "scoped_multi_pub" | ...
    nav_pubs          : list[str] = Field(default_factory=list)   # pubs identified by navigation
    ontology_pubs     : list[str] = Field(default_factory=list)   # pubs added by ontology routing

    @property
    def total_tokens(self) -> int:
        return self.prompt_tokens + self.completion_tokens

    @property
    def sources(self) -> list[str]:
        """Deduplicated citation strings from retrieved contexts."""
        seen: set[str] = set()
        out: list[str] = []
        for ctx in self.contexts:
            c = ctx.citation
            if c not in seen:
                seen.add(c)
                out.append(c)
        return out

    def print_report(self, show_contexts: bool = False) -> None:
        """Pretty-print the query result to stdout."""
        width = 72
        print(f"\n{'─' * width}")
        print(f"Query: {self.query}")
        print(f"{'─' * width}")

        if self.error:
            print(f"\n⚠  Synthesis error: {self.error}\n")

        if self.answer:
            print(f"\n{self.answer}\n")

        print(f"{'─' * width}")
        method_counts: dict[str, int] = {}
        for ctx in self.contexts:
            method_counts[ctx.retrieval_method] = method_counts.get(ctx.retrieval_method, 0) + 1
        method_str = "  ".join(f"{m}={n}" for m, n in sorted(method_counts.items()))
        print(f"Sources ({len(self.contexts)} chunks retrieved  [{method_str}]):")
        for i, ctx in enumerate(self.contexts, 1):
            print(f"  [{i}] {ctx.citation}  (score={ctx.score:.3f}  {ctx.retrieval_method})")
            if show_contexts:
                print(f"      {ctx.snippet}")

        stats = []
        if self.retrieval_mode:
            stats.append(f"mode={self.retrieval_mode}")
        if self.retrieval_ms:
            stats.append(f"retrieval {self.retrieval_ms:.0f} ms")
        if self.synthesis_ms:
            stats.append(f"synthesis {self.synthesis_ms:.0f} ms")
        if self.model_used:
            stats.append(self.model_used)
        if self.total_tokens:
            stats.append(f"{self.total_tokens} tokens")
        if stats:
            print(f"\n  {' | '.join(stats)}")
        if self.nav_pubs:
            print(f"  Navigation pubs: {', '.join(self.nav_pubs)}")
        if self.ontology_pubs:
            print(f"  Ontology augmented: {', '.join(self.ontology_pubs)}")
        print()
