"""baseline: uuid7 schema

Revision ID: 43cbaf69e152
Revises: 
Create Date: 2026-04-16 16:55:57.207484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cbaf69e152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('auth0_sub', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('family_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('primary_first_name', sa.String(length=100), nullable=False),
    sa.Column('primary_last_name', sa.String(length=100), nullable=False),
    sa.Column('spouse_first_name', sa.String(length=100), nullable=True),
    sa.Column('spouse_last_name', sa.String(length=100), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_groups_org_id'), 'family_groups', ['org_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primary_first_name', sa.String(length=100), nullable=True),
    sa.Column('primary_last_name', sa.String(length=100), nullable=True),
    sa.Column('filing_status', sa.String(length=10), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('workflow_step', sa.String(length=20), nullable=False),
    sa.Column('family_group_id', sa.String(length=36), nullable=True),
    sa.Column('primary_ssn_enc', sa.LargeBinary(), nullable=True),
    sa.Column('primary_dob_enc', sa.LargeBinary(), nullable=True),
    sa.Column('spouse_ssn_enc', sa.LargeBinary(), nullable=True),
    sa.Column('spouse_dob_enc', sa.LargeBinary(), nullable=True),
    sa.Column('street_enc', sa.LargeBinary(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('spouse_email', sa.String(length=254), nullable=True),
    sa.Column('spouse_phone', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_org_created_by', 'clients', ['org_id', 'created_by'], unique=False)
    op.create_index(op.f('ix_clients_org_id'), 'clients', ['org_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_client_id'), 'chat_messages', ['client_id'], unique=False)
    op.create_index('ix_chat_messages_org_client', 'chat_messages', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_org_id'), 'chat_messages', ['org_id'], unique=False)
    op.create_table('dependents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('ssn_enc', sa.LargeBinary(), nullable=True),
    sa.Column('dob_enc', sa.LargeBinary(), nullable=True),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('months_lived_with', sa.Integer(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_qualifying_child', sa.Boolean(), nullable=False),
    sa.Column('is_us_citizen', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_client_id'), 'dependents', ['client_id'], unique=False)
    op.create_index('ix_dependents_org_client', 'dependents', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_dependents_org_id'), 'dependents', ['org_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_data', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_data_enc', sa.LargeBinary(), nullable=True),
    sa.Column('file_content_enc', sa.LargeBinary(), nullable=True),
    sa.Column('file_content_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('flags', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index('ix_documents_org_client', 'documents', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_table('manual_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('form_type', sa.String(length=30), nullable=False),
    sa.Column('form_index', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('entered_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_entries_client_id'), 'manual_entries', ['client_id'], unique=False)
    op.create_index('ix_manual_entries_org_client', 'manual_entries', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_manual_entries_org_id'), 'manual_entries', ['org_id'], unique=False)
    op.create_table('tax_return_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('filing_status', sa.String(length=10), nullable=False),
    sa.Column('draft_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'client_id', name='uq_draft_org_client')
    )
    op.create_index('ix_drafts_org_client', 'tax_return_drafts', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_tax_return_drafts_client_id'), 'tax_return_drafts', ['client_id'], unique=False)
    op.create_index(op.f('ix_tax_return_drafts_org_id'), 'tax_return_drafts', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_return_drafts_org_id'), table_name='tax_return_drafts')
    op.drop_index(op.f('ix_tax_return_drafts_client_id'), table_name='tax_return_drafts')
    op.drop_index('ix_drafts_org_client', table_name='tax_return_drafts')
    op.drop_table('tax_return_drafts')
    op.drop_index(op.f('ix_manual_entries_org_id'), table_name='manual_entries')
    op.drop_index('ix_manual_entries_org_client', table_name='manual_entries')
    op.drop_index(op.f('ix_manual_entries_client_id'), table_name='manual_entries')
    op.drop_table('manual_entries')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index('ix_documents_org_client', table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dependents_org_id'), table_name='dependents')
    op.drop_index('ix_dependents_org_client', table_name='dependents')
    op.drop_index(op.f('ix_dependents_client_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_chat_messages_org_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_org_client', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_client_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_clients_org_id'), table_name='clients')
    op.drop_index('ix_clients_org_created_by', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_family_groups_org_id'), table_name='family_groups')
    op.drop_table('family_groups')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
