"""add conversation_type and nullable client_id for research

Revision ID: 8131925e09ad
Revises: 51956d2c9486
Create Date: 2026-04-17 16:09:29.352898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8131925e09ad'
down_revision: Union[str, Sequence[str], None] = '51956d2c9486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_type', sa.String(length=20), nullable=False))
    op.alter_column('conversations', 'client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index('ix_conv_type_user', 'conversations', ['conversation_type', 'user_id', 'org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conv_type_user', table_name='conversations')
    op.alter_column('conversations', 'client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('conversations', 'conversation_type')
    # ### end Alembic commands ###
