"""add filing_federal and filing_states

Revision ID: e41e2d4e91b6
Revises: 43cbaf69e152
Create Date: 2026-04-16 17:26:22.232791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41e2d4e91b6'
down_revision: Union[str, Sequence[str], None] = '43cbaf69e152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Server defaults so existing rows backfill on add. New inserts get the
    # value from the SQLAlchemy column default (True / "[]").
    op.add_column(
        'clients',
        sa.Column('filing_federal', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'clients',
        sa.Column('filing_states', sa.Text(), nullable=False, server_default='[]'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'filing_states')
    op.drop_column('clients', 'filing_federal')
    # ### end Alembic commands ###
