"""Tier 2: Text layer extraction for readable/programmatic PDFs using pdfplumber.

Extracts structured data from PDFs that have embedded text (generated by
payroll systems like ADP, Gusto, QuickBooks — not scanned images).

Uses two strategies:
1. Table extraction — pdfplumber's table detection finds cell-by-cell data
2. Regex text extraction — pattern matching on the full text as fallback

This tier is free, instant, and gives 100% accurate numbers since it reads
the actual text embedded in the PDF rather than interpreting an image.
"""
import io
import re
from decimal import Decimal, InvalidOperation

import pdfplumber
from pypdf import PdfReader

from api.models.document import ExtractionResult, ExtractedField

# ── Currency/value parsing ───────────────────────────────────────────────────

_CURRENCY_RE = re.compile(
    r"""(?x)
    (?:
        \$\s*(\d{1,3}(?:,\d{3})*(?:\.\d{2})?|\d+(?:\.\d{2})?)
        |
        (\d{1,3}(?:,\d{3})+(?:\.\d{2})?)
        |
        (\d+\.\d{2})
    )
    """
)

_EIN_RE = re.compile(r"\b(\d{2}-\d{7})\b")
_SSN_RE = re.compile(r"\b(\d{3}-\d{2}-\d{4})\b")


def _parse_currency(s: str) -> str:
    """Parse a currency/number string to clean decimal format."""
    if not s:
        return ""
    s = s.replace(",", "").replace("$", "").strip()
    try:
        d = Decimal(s)
        return f"{d:.2f}"
    except (InvalidOperation, ValueError):
        return ""


def _extract_number(s: str) -> str:
    """Extract a number from a string that may contain labels."""
    if not s:
        return ""
    s = s.strip()
    # Try direct parse first
    result = _parse_currency(s)
    if result:
        return result
    # Try to find a number in the string
    m = _CURRENCY_RE.search(s)
    if m:
        raw = m.group(1) or m.group(2) or m.group(3) or ""
        return _parse_currency(raw)
    # Try bare integer
    m = re.search(r"\b(\d{4,})\b", s)
    if m:
        return _parse_currency(m.group(1))
    return ""


def _find_amount_after_label(text: str, patterns: list[str], window: int = 300) -> str:
    """Find a currency amount appearing after a label pattern in the text.
    Handles both same-line and next-line value placement.
    """
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if not match:
            continue
        search_area = text[match.end():match.end() + window]
        # Try currency pattern first
        amt_match = _CURRENCY_RE.search(search_area)
        if amt_match:
            raw = amt_match.group(1) or amt_match.group(2) or amt_match.group(3) or ""
            result = _parse_currency(raw)
            if result:
                return result
        # Try bare number on next line
        lines = search_area.strip().split("\n")
        for line in lines[:3]:
            line = line.strip()
            m = re.match(r"^[\$]?\s*(\d[\d,]*\.?\d*)\s*$", line)
            if m:
                result = _parse_currency(m.group(1))
                if result:
                    return result
    return ""


def _find_text_after_label(text: str, patterns: list[str], window: int = 150) -> str:
    """Find text immediately after a label pattern."""
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if not match:
            continue
        remaining = text[match.end():match.end() + window].strip()
        line = remaining.split("\n")[0].strip()
        # Skip if it's just a number or too short
        if line and len(line) > 1 and not re.match(r"^\d+\.?\d*$", line):
            return line
    return ""


# ── Format detection ─────────────────────────────────────────────────────────

def detect_pdf_format(file_bytes: bytes) -> str:
    """Detect PDF format: 'acroform', 'text', 'scanned', 'image', or 'not_pdf'."""
    if not file_bytes[:5].startswith(b"%PDF"):
        if file_bytes[:8] == b"\x89PNG\r\n\x1a\n" or file_bytes[:2] == b"\xff\xd8":
            return "image"
        return "not_pdf"

    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        fields = reader.get_form_text_fields() or {}
        if len(fields) >= 2:
            return "acroform"
    except Exception:
        pass

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            for page in pdf.pages[:3]:
                text = (page.extract_text() or "").strip()
                if len(text) > 20:
                    return "text"
    except Exception:
        pass

    return "scanned"


# ── Form classification ──────────────────────────────────────────────────────

def _classify_form(text: str, filename_hint: str = "") -> str:
    """Classify the tax form type from text content and filename."""
    fname = filename_hint.lower()
    text_lower = text.lower()

    if "w2" in fname or "w-2" in fname:
        return "W-2"
    if "1099-int" in fname or "1099int" in fname:
        return "1099-INT"
    if "1099-div" in fname or "1099div" in fname:
        return "1099-DIV"
    if "1099-b" in fname or "1099b" in fname:
        return "1099-B"
    if "1099-nec" in fname or "1099nec" in fname:
        return "1099-NEC"
    if "1098" in fname:
        return "1098"
    if "k-1" in fname or "k1" in fname:
        return "K-1"

    if "wage and tax statement" in text_lower or "w-2" in text_lower:
        return "W-2"
    if "interest income" in text_lower and "1099" in text_lower:
        return "1099-INT"
    if "dividends and distributions" in text_lower or "1099-div" in text_lower:
        return "1099-DIV"
    if "proceeds from broker" in text_lower or "1099-b" in text_lower:
        return "1099-B"
    if "nonemployee compensation" in text_lower or "1099-nec" in text_lower:
        return "1099-NEC"
    if "mortgage interest" in text_lower and "1098" in text_lower:
        return "1098"
    if "schedule k-1" in text_lower or "share of income" in text_lower:
        return "K-1"

    return "Other"


# ── W-2 Table-based extraction ───────────────────────────────────────────────

def _extract_w2_from_table(tables: list, text: str) -> list[ExtractedField]:
    """Extract W-2 data from pdfplumber table cells — handles grid layout."""
    fields = []

    # Flatten all table cells into a searchable structure
    # Each cell may contain "label\nvalue" (e.g., "1 Wages...\n160000")
    cell_texts = []
    for table in tables:
        for row in table:
            for cell in row:
                if cell:
                    cell_texts.append(cell.strip())

    def _find_in_cells(label_patterns: list[str]) -> str:
        """Find a value in table cells where label and value are in same cell."""
        for cell in cell_texts:
            for pattern in label_patterns:
                if re.search(pattern, cell, re.IGNORECASE):
                    # Value is usually after a newline in the same cell
                    lines = cell.split("\n")
                    for line in lines[1:]:
                        val = _extract_number(line)
                        if val:
                            return val
                    # Or value might be a number at the end of the cell
                    val = _extract_number(lines[-1]) if len(lines) == 1 else ""
                    if val:
                        return val
        return ""

    def _find_text_in_cells(label_patterns: list[str]) -> str:
        """Find text (not number) after label in cells."""
        for cell in cell_texts:
            for pattern in label_patterns:
                if re.search(pattern, cell, re.IGNORECASE):
                    lines = cell.split("\n")
                    for line in lines[1:]:
                        line = line.strip()
                        if line and not re.match(r"^\d+$", line) and len(line) > 2:
                            # Clean up — remove trailing location codes etc
                            return line.split(",")[0].strip() if "," in line else line
        return ""

    # Employer EIN
    ein_val = _find_in_cells([r"employer\s+identification\s+number", r"\bEIN\b"])
    if not ein_val:
        m = _EIN_RE.search(text)
        if m:
            ein_val = m.group(1)
    if ein_val:
        # EIN might be a plain number — format it
        if re.match(r"^\d{9}$", ein_val.replace(".", "").replace("-", "")):
            clean = ein_val.replace("-", "").replace(".", "")[:9]
            ein_val = f"{clean[:2]}-{clean[2:]}"
        fields.append(ExtractedField(name="employer_ein", value=ein_val, confidence=0.98))

    # Employer name
    employer = _find_text_in_cells([r"employer.s?\s+name", r"c\s+employer"])
    if employer:
        fields.append(ExtractedField(name="employer_name", value=employer, confidence=0.95))

    # Box 1: Wages
    wages = _find_in_cells([r"1\s+wages", r"wages.*compensation"])
    if wages:
        fields.append(ExtractedField(name="box1_wages", value=wages, confidence=0.99))

    # Box 2: Federal tax withheld
    fed = _find_in_cells([r"2\s+federal\s+income\s+tax", r"federal.*tax.*withheld"])
    if fed:
        fields.append(ExtractedField(name="box2_fed_withheld", value=fed, confidence=0.99))

    # Box 3: Social Security wages
    ss_wages = _find_in_cells([r"3\s+social\s+security\s+wages", r"social\s+security\s+wages"])
    if ss_wages:
        fields.append(ExtractedField(name="box3_ss_wages", value=ss_wages, confidence=0.99))

    # Box 4: Social Security tax withheld
    ss_tax = _find_in_cells([r"4\s+social\s+security\s+tax", r"social\s+security\s+tax"])
    if ss_tax:
        fields.append(ExtractedField(name="box4_ss_withheld", value=ss_tax, confidence=0.99))

    # Box 5: Medicare wages
    med_wages = _find_in_cells([r"5\s+medicare\s+wages", r"medicare\s+wages"])
    if med_wages:
        fields.append(ExtractedField(name="box5_medicare_wages", value=med_wages, confidence=0.99))

    # Box 6: Medicare tax withheld
    med_tax = _find_in_cells([r"6\s+medicare\s+tax", r"medicare\s+tax"])
    if med_tax:
        fields.append(ExtractedField(name="box6_medicare_withheld", value=med_tax, confidence=0.99))

    # Box 15-17: State
    state_cell = _find_text_in_cells([r"15\s+state", r"state.*employer"])
    if state_cell:
        # Extract state abbreviation (2 letters)
        m = re.match(r"([A-Z]{2})", state_cell)
        if m:
            fields.append(ExtractedField(name="box15_state", value=m.group(1), confidence=0.98))

    state_wages = _find_in_cells([r"16\s+state\s+wages", r"state\s+wages"])
    if state_wages:
        fields.append(ExtractedField(name="box16_state_wages", value=state_wages, confidence=0.99))

    state_tax = _find_in_cells([r"17\s+state\s+income\s+tax", r"state\s+income\s+tax"])
    if state_tax:
        fields.append(ExtractedField(name="box17_state_withheld", value=state_tax, confidence=0.99))

    return fields


# ── Per-form text extraction (fallback for non-table PDFs) ───────────────────

def _extract_w2_text(text: str) -> list[ExtractedField]:
    """Extract W-2 fields from plain text (fallback)."""
    fields = []

    employer = _find_text_after_label(text, [r"employer.s?\s+name", r"c\s+employer"])
    if employer:
        fields.append(ExtractedField(name="employer_name", value=employer, confidence=0.90))

    ein_match = _EIN_RE.search(text)
    if ein_match:
        fields.append(ExtractedField(name="employer_ein", value=ein_match.group(1), confidence=0.95))

    for field_name, patterns in [
        ("box1_wages", [r"1\s+wages", r"wages.*compensation"]),
        ("box2_fed_withheld", [r"2\s+federal.*tax.*withheld", r"federal.*tax.*withheld"]),
        ("box3_ss_wages", [r"3\s+social\s+security\s+wages"]),
        ("box4_ss_withheld", [r"4\s+social\s+security\s+tax"]),
        ("box5_medicare_wages", [r"5\s+medicare\s+wages"]),
        ("box6_medicare_withheld", [r"6\s+medicare\s+tax"]),
    ]:
        val = _find_amount_after_label(text, patterns)
        if val:
            fields.append(ExtractedField(name=field_name, value=val, confidence=0.95))

    return fields


def _extract_1099_int(text: str, tables: list) -> list[ExtractedField]:
    fields = []
    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))
    interest = _find_amount_after_label(text, [r"1\s+interest\s+income", r"interest\s+income"])
    if interest:
        fields.append(ExtractedField(name="box1_interest", value=interest, confidence=0.98))
    withheld = _find_amount_after_label(text, [r"4\s+federal.*withheld", r"federal.*tax.*withheld"])
    if withheld:
        fields.append(ExtractedField(name="box4_fed_withheld", value=withheld, confidence=0.98))
    return fields


def _extract_1099_div(text: str, tables: list) -> list[ExtractedField]:
    fields = []
    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))
    for name, patterns in [
        ("box1a_ordinary_dividends", [r"1a\s+(?:total\s+)?ordinary\s+dividends"]),
        ("box1b_qualified_dividends", [r"1b\s+qualified\s+dividends"]),
        ("box2a_capital_gain_distributions", [r"2a\s+.*capital\s+gain"]),
    ]:
        val = _find_amount_after_label(text, patterns)
        if val:
            fields.append(ExtractedField(name=name, value=val, confidence=0.98))
    return fields


def _extract_1099_nec(text: str, tables: list) -> list[ExtractedField]:
    fields = []
    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))
    comp = _find_amount_after_label(text, [r"1\s+nonemployee\s+compensation", r"nonemployee\s+compensation"])
    if comp:
        fields.append(ExtractedField(name="nec_compensation", value=comp, confidence=0.98))
    return fields


def _extract_1098(text: str, tables: list) -> list[ExtractedField]:
    fields = []
    lender = _find_text_after_label(text, [r"recipient.s?\s+name", r"lender\s*:"])
    if lender:
        fields.append(ExtractedField(name="lender", value=lender, confidence=0.95))
    interest = _find_amount_after_label(text, [r"1\s+mortgage\s+interest", r"mortgage\s+interest"])
    if interest:
        fields.append(ExtractedField(name="box1_interest", value=interest, confidence=0.98))
    taxes = _find_amount_after_label(text, [r"10\s+property\s+tax", r"property\s+tax"])
    if taxes:
        fields.append(ExtractedField(name="box10_property_taxes", value=taxes, confidence=0.98))
    return fields


# ── Main extractor class ─────────────────────────────────────────────────────

class TextLayerExtractor:
    """Extracts structured data from PDFs with embedded text using pdfplumber."""

    async def extract(self, file_bytes: bytes, form_type: str) -> ExtractionResult:
        try:
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                pages_text = []
                all_tables = []
                for page in pdf.pages[:10]:
                    text = page.extract_text() or ""
                    if text.strip():
                        pages_text.append(text)
                    tables = page.extract_tables()
                    if tables:
                        all_tables.extend(tables)
                full_text = "\n".join(pages_text)
        except Exception:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=["Failed to read PDF text layer"],
            )

        if not full_text or len(full_text.strip()) < 20:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=["No text layer found — document may be scanned"],
            )

        # Auto-classify if needed
        detected_type = form_type
        if form_type in ("Other", "1099", ""):
            detected_type = _classify_form(full_text)

        # Extract using table-aware strategy
        fields = self._extract_form(detected_type, full_text, all_tables)

        if not fields:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=[f"Text layer found but no fields extracted for '{detected_type}'"],
            )

        min_conf = min(f.confidence for f in fields)
        has_flags = any(f.flagged for f in fields)
        flag_msgs = [f.flag_reason for f in fields if f.flagged and f.flag_reason]

        return ExtractionResult(
            fields=fields, overall_confidence=min_conf,
            has_flags=has_flags, flags=flag_msgs,
        )

    def _extract_form(self, form_type: str, text: str, tables: list) -> list[ExtractedField]:
        """Route to form-specific extractor."""
        if form_type == "W-2":
            # Try table-based extraction first (handles grid layouts)
            if tables:
                fields = _extract_w2_from_table(tables, text)
                if len(fields) >= 3:  # Got meaningful data from tables
                    return fields
            # Fallback to text-based
            return _extract_w2_text(text)
        elif form_type == "1099-INT":
            return _extract_1099_int(text, tables)
        elif form_type == "1099-DIV":
            return _extract_1099_div(text, tables)
        elif form_type == "1099-NEC":
            return _extract_1099_nec(text, tables)
        elif form_type == "1098":
            return _extract_1098(text, tables)
        return []
