"""Tier 2: Text layer extraction for readable/programmatic PDFs using pdfplumber.

Extracts structured data from PDFs that have embedded text (generated by
payroll systems like ADP, Gusto, QuickBooks — not scanned images).

This tier is free, instant, and gives 100% accurate numbers since it reads
the actual text embedded in the PDF rather than interpreting an image.
"""
import io
import re
from decimal import Decimal

import pdfplumber
from pypdf import PdfReader

from api.models.document import ExtractionResult, ExtractedField

# ── Currency parsing ─────────────────────────────────────────────────────────

_CURRENCY_RE = re.compile(
    r"""(?x)
    (?:
        \$\s*(\d{1,3}(?:,\d{3})*(?:\.\d{2})?|\d+(?:\.\d{2})?)   # $-prefixed
        |
        (\d{1,3}(?:,\d{3})+(?:\.\d{2})?)                          # With comma separators
        |
        (\d+\.\d{2})                                                # Decimal with 2 digits
    )
    """
)

_EIN_RE = re.compile(r"\b(\d{2}-\d{7})\b")
_SSN_RE = re.compile(r"\b(\d{3}-\d{2}-\d{4})\b")


def _parse_currency(s: str) -> str:
    """Parse a currency string to clean decimal. Returns '' if not found."""
    if not s:
        return ""
    s = s.replace(",", "").replace("$", "").strip()
    try:
        return f"{Decimal(s):.2f}"
    except Exception:
        return ""


def _find_amount_after_label(text: str, patterns: list[str], window: int = 200) -> str:
    """Find a currency amount appearing after a label pattern in the text."""
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if not match:
            continue
        search_area = text[match.end():match.end() + window]
        amt_match = _CURRENCY_RE.search(search_area)
        if amt_match:
            raw = amt_match.group(1) or amt_match.group(2) or amt_match.group(3) or ""
            return _parse_currency(raw)
    return ""


def _find_text_after_label(text: str, patterns: list[str], window: int = 100) -> str:
    """Find text immediately after a label pattern."""
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if not match:
            continue
        remaining = text[match.end():match.end() + window].strip()
        # Take the first line/chunk of text
        line = remaining.split("\n")[0].strip()
        if line and len(line) > 1:
            return line
    return ""


# ── Format detection ─────────────────────────────────────────────────────────

def detect_pdf_format(file_bytes: bytes) -> str:
    """Detect the PDF format: 'acroform', 'text', 'scanned', or 'not_pdf'.

    Returns which extraction tier to use:
    - 'acroform': Has fillable form fields → Tier 1
    - 'text': Has embedded text layer → Tier 2
    - 'scanned': No text, likely scanned image → Tier 3 (Vision AI)
    - 'not_pdf': Not a PDF file
    """
    if not file_bytes[:5].startswith(b"%PDF"):
        if file_bytes[:8] == b"\x89PNG\r\n\x1a\n" or file_bytes[:2] == b"\xff\xd8":
            return "image"
        return "not_pdf"

    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        fields = reader.get_form_text_fields() or {}
        if len(fields) >= 2:
            return "acroform"
    except Exception:
        pass

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            for page in pdf.pages[:3]:
                text = (page.extract_text() or "").strip()
                if len(text) > 20:
                    return "text"
    except Exception:
        pass

    return "scanned"


# ── Form classification ──────────────────────────────────────────────────────

def _classify_form(text: str, filename_hint: str = "") -> str:
    """Classify the tax form type from its text content and filename."""
    fname = filename_hint.lower()
    text_lower = text.lower()

    # Filename heuristics first
    if "w2" in fname or "w-2" in fname:
        return "W-2"
    if "1099-int" in fname or "1099int" in fname:
        return "1099-INT"
    if "1099-div" in fname or "1099div" in fname:
        return "1099-DIV"
    if "1099-b" in fname or "1099b" in fname:
        return "1099-B"
    if "1099-nec" in fname or "1099nec" in fname:
        return "1099-NEC"
    if "1098" in fname:
        return "1098"
    if "k-1" in fname or "k1" in fname:
        return "K-1"

    # Text content heuristics
    if "wage and tax statement" in text_lower or ("w-2" in text_lower and "wages" in text_lower):
        return "W-2"
    if "interest income" in text_lower and "1099-int" in text_lower:
        return "1099-INT"
    if "dividends and distributions" in text_lower or "1099-div" in text_lower:
        return "1099-DIV"
    if "proceeds from broker" in text_lower or "1099-b" in text_lower:
        return "1099-B"
    if "nonemployee compensation" in text_lower or "1099-nec" in text_lower:
        return "1099-NEC"
    if "mortgage interest" in text_lower and "1098" in text_lower:
        return "1098"
    if ("schedule k-1" in text_lower or "partner" in text_lower) and "share of income" in text_lower:
        return "K-1"

    return "Other"


# ── Per-form extraction ──────────────────────────────────────────────────────

def _extract_w2(text: str) -> list[ExtractedField]:
    """Extract W-2 fields from text."""
    fields = []

    # Employer name — look for text near "employer" label
    employer = _find_text_after_label(text, [
        r"employer.s?\s+name", r"employer\s*:", r"c\s+employer",
    ])
    if employer:
        fields.append(ExtractedField(name="employer_name", value=employer, confidence=0.95))

    # EIN
    ein_match = _EIN_RE.search(text)
    if ein_match:
        fields.append(ExtractedField(name="employer_ein", value=ein_match.group(1), confidence=0.95))

    # Box 1: Wages
    wages = _find_amount_after_label(text, [
        r"(?:box\s*)?1\s+wages", r"wages,?\s+(?:salaries,?\s+)?tips",
        r"wages.*compensation",
    ])
    if wages:
        fields.append(ExtractedField(name="box1_wages", value=wages, confidence=0.98))

    # Box 2: Federal tax withheld
    withheld = _find_amount_after_label(text, [
        r"(?:box\s*)?2\s+federal\s+(?:income\s+)?tax\s+withheld",
        r"federal\s+(?:income\s+)?tax\s+withheld",
        r"fed(?:eral)?\s+(?:tax\s+)?withheld",
    ])
    if withheld:
        fields.append(ExtractedField(name="box2_fed_withheld", value=withheld, confidence=0.98))

    # Box 3: Social Security wages
    ss_wages = _find_amount_after_label(text, [
        r"(?:box\s*)?3\s+social\s+security\s+wages",
        r"social\s+security\s+wages",
    ])
    if ss_wages:
        fields.append(ExtractedField(name="box3_ss_wages", value=ss_wages, confidence=0.98))

    # Box 4: Social Security tax withheld
    ss_tax = _find_amount_after_label(text, [
        r"(?:box\s*)?4\s+social\s+security\s+tax",
        r"social\s+security\s+tax\s+withheld",
    ])
    if ss_tax:
        fields.append(ExtractedField(name="box4_ss_withheld", value=ss_tax, confidence=0.98))

    # Box 5: Medicare wages
    med_wages = _find_amount_after_label(text, [
        r"(?:box\s*)?5\s+medicare\s+wages",
        r"medicare\s+wages",
    ])
    if med_wages:
        fields.append(ExtractedField(name="box5_medicare_wages", value=med_wages, confidence=0.98))

    # Box 6: Medicare tax withheld
    med_tax = _find_amount_after_label(text, [
        r"(?:box\s*)?6\s+medicare\s+tax",
        r"medicare\s+tax\s+withheld",
    ])
    if med_tax:
        fields.append(ExtractedField(name="box6_medicare_withheld", value=med_tax, confidence=0.98))

    return fields


def _extract_1099_int(text: str) -> list[ExtractedField]:
    """Extract 1099-INT fields from text."""
    fields = []

    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))

    interest = _find_amount_after_label(text, [
        r"(?:box\s*)?1\s+interest\s+income", r"interest\s+income",
    ])
    if interest:
        fields.append(ExtractedField(name="box1_interest", value=interest, confidence=0.98))

    withheld = _find_amount_after_label(text, [
        r"(?:box\s*)?4\s+federal.*withheld", r"federal.*tax.*withheld",
    ])
    if withheld:
        fields.append(ExtractedField(name="box4_fed_withheld", value=withheld, confidence=0.98))

    return fields


def _extract_1099_div(text: str) -> list[ExtractedField]:
    """Extract 1099-DIV fields from text."""
    fields = []

    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))

    ordinary = _find_amount_after_label(text, [
        r"(?:box\s*)?1a\s+(?:total\s+)?ordinary\s+dividends",
        r"total\s+ordinary\s+dividends",
    ])
    if ordinary:
        fields.append(ExtractedField(name="box1a_ordinary_dividends", value=ordinary, confidence=0.98))

    qualified = _find_amount_after_label(text, [
        r"(?:box\s*)?1b\s+qualified\s+dividends", r"qualified\s+dividends",
    ])
    if qualified:
        fields.append(ExtractedField(name="box1b_qualified_dividends", value=qualified, confidence=0.98))

    cap_gain = _find_amount_after_label(text, [
        r"(?:box\s*)?2a\s+.*capital\s+gain", r"total\s+capital\s+gain",
    ])
    if cap_gain:
        fields.append(ExtractedField(name="box2a_capital_gain_distributions", value=cap_gain, confidence=0.98))

    return fields


def _extract_1099_nec(text: str) -> list[ExtractedField]:
    """Extract 1099-NEC fields from text."""
    fields = []

    payer = _find_text_after_label(text, [r"payer.s?\s+name", r"payer\s*:"])
    if payer:
        fields.append(ExtractedField(name="payer", value=payer, confidence=0.95))

    comp = _find_amount_after_label(text, [
        r"(?:box\s*)?1\s+nonemployee\s+compensation",
        r"nonemployee\s+compensation",
    ])
    if comp:
        fields.append(ExtractedField(name="nec_compensation", value=comp, confidence=0.98))

    return fields


def _extract_1098(text: str) -> list[ExtractedField]:
    """Extract 1098 fields from text."""
    fields = []

    lender = _find_text_after_label(text, [r"recipient.s?\s+name", r"lender\s*:"])
    if lender:
        fields.append(ExtractedField(name="lender", value=lender, confidence=0.95))

    interest = _find_amount_after_label(text, [
        r"(?:box\s*)?1\s+mortgage\s+interest", r"mortgage\s+interest\s+received",
    ])
    if interest:
        fields.append(ExtractedField(name="box1_interest", value=interest, confidence=0.98))

    taxes = _find_amount_after_label(text, [
        r"(?:box\s*)?10\s+property\s+tax", r"property\s+tax",
    ])
    if taxes:
        fields.append(ExtractedField(name="box10_property_taxes", value=taxes, confidence=0.98))

    return fields


_FORM_EXTRACTORS = {
    "W-2": _extract_w2,
    "1099-INT": _extract_1099_int,
    "1099-DIV": _extract_1099_div,
    "1099-NEC": _extract_1099_nec,
    "1098": _extract_1098,
}


# ── Main extractor class ─────────────────────────────────────────────────────

class TextLayerExtractor:
    """Extracts structured data from PDFs with embedded text using pdfplumber.

    Best for readable/programmatic PDFs generated by payroll systems (ADP, Gusto,
    QuickBooks). Gives 100% accurate numbers since it reads actual embedded text.
    """

    async def extract(self, file_bytes: bytes, form_type: str) -> ExtractionResult:
        """Extract fields from a PDF's text layer.

        Returns ExtractionResult with fields, or empty result if no text found.
        """
        # Extract text from all pages
        try:
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                pages_text = []
                for page in pdf.pages[:10]:
                    text = page.extract_text() or ""
                    if text.strip():
                        pages_text.append(text)
                full_text = "\n".join(pages_text)
        except Exception:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=["Failed to read PDF text layer"],
            )

        if not full_text or len(full_text.strip()) < 20:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=["No text layer found — document may be scanned"],
            )

        # Auto-classify form if type is "Other" or unknown
        detected_type = form_type
        if form_type in ("Other", "1099", ""):
            detected_type = _classify_form(full_text)

        # Run form-specific extractor
        extractor_fn = _FORM_EXTRACTORS.get(detected_type)
        if not extractor_fn:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=[f"No text extraction rules for form type '{detected_type}'"],
            )

        fields = extractor_fn(full_text)
        if not fields:
            return ExtractionResult(
                fields=[], overall_confidence=0.0, has_flags=True,
                flags=["Text layer found but no fields could be extracted"],
            )

        min_conf = min(f.confidence for f in fields) if fields else 0.0
        has_flags = any(f.flagged for f in fields)
        flag_msgs = [f.flag_reason for f in fields if f.flagged and f.flag_reason]

        return ExtractionResult(
            fields=fields,
            overall_confidence=min_conf,
            has_flags=has_flags,
            flags=flag_msgs,
        )
